name: repaso-jakarta
services:
  tomee:
    image: tomee:jre21-webprofile
    container_name: tomee_trivial
    ports:
      - "8685:8080"
    volumes:
      - ./target:/usr/local/tomee/webapps
    depends_on:
      - db

  db:
    image: mysql:8.0.34
    container_name: mysql_db_trivial
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: repaso
      MYSQL_USER: cristian
      MYSQL_PASSWORD: secret
    ports:
      - "3396:3306"
    volumes:
      - db_repaso:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin_trivial
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8686:80"
    depends_on:
      - db

volumes:
  db_repaso: